#pragma once

#include <VCLG/CodeGen/GraphLayout.hpp>
#include <VCLG/Graph/Elaboration.hpp>
#include <VCLG/Translation/NodeInterface.hpp>

#include <VCL/AST/ConstantValue.hpp>
#include <VCL/AST/Type.hpp>

#include <llvm/ADT/FunctionExtras.h>
#include <llvm/ADT/SmallVector.h>

#include <cstdint>
#include <optional>
#include <set>
#include <string>
#include <vector>


namespace VCLG {

    /**
     * A frame is a function generated by graph codegen that runs a set of nodes (`state-as-data.md`
     * §5.4). The root frame is `Main`: its host slots are bound symbols. An instance frame (a
     * subgraph compiled once and run once per instance, plan P11) reaches them from a base pointer;
     * it doesn't exist yet.
     */
    enum class FrameKind { Root, Instance };

    /**
     * Where every piece of storage a frame passes to its nodes lives (`state-as-data.md` §5.2,
     * §5.3), decided once per compile, before the frame is emitted.
     *
     * A slot is one piece of storage. Nodes refer to slots by index: an input connected without a
     * converter shares its producer's output slot, and so does whatever reads a Subgraph Input or
     * Output copying a value through.
     */
    struct SlotPlan {
        static constexpr uint32_t None = UINT32_MAX;

        enum class SlotClass {
            /** S1: a node's `State`, in the state block. */
            HostState,
            /** S3: an output that must persist or is observed, in the state block. */
            HostPort,
            /** S4: an always-written output, or a converter's result: an `alloca` of the frame. */
            Temporary,
            /** S5: the value a Feedback Input carries to the next call, in the state block. */
            Feedback,
            /** S6: an unconnected input: a constant. */
            Constant
        };

        struct Slot {
            SlotClass slotClass = SlotClass::Constant;
            /** The slot's VCL type (null for a State, known only by its size). */
            VCL::Type* type = nullptr;
            uint64_t size = 0;
            uint64_t alignment = 1;
            /** What the slot holds, for diagnostics and printing (`g1/n3.output`, `g1/n3`, ...). */
            std::string name{};

            /** Host classes: the region in the layout. */
            uint32_t region = None;

            /**
             * Temporaries: live from the call at position `first` in the execution order to the one
             * at `last`, both included; the frame's end (feedback copies) is position
             * `order.size()`. `isOutput` when the temporary is a node's output, which the node
             * always writes (the debug canary checks it after the call).
             */
            uint32_t first = 0;
            uint32_t last = 0;
            bool isOutput = false;

            /**
             * Constants: the scalar the graph gives the input (splat across vectors and lanes), or
             * else the variant's constant holding the declared initializer (`defaultValue`, a symbol
             * of the module), or else zero.
             */
            std::optional<VCL::ConstantScalar> value{};
            std::string defaultValue{};
        };

        struct NodeSlots {
            /** Source nodes: the slot of their `State`. */
            uint32_t state = None;
            llvm::SmallVector<uint32_t, 4> inputs{};
            llvm::SmallVector<uint32_t, 4> outputs{};
        };

        /** The end-of-frame copy of a feedback edge's value into its region (§5.6). */
        struct FeedbackCopy {
            ElaboratedGraph::NodeIndex feedbackInput = ElaboratedGraph::Invalid;
            uint32_t from = None;
            uint32_t to = None;
        };

        FrameKind frame = FrameKind::Root;
        std::vector<Slot> slots{};
        /** Indexed like the elaborated graph's nodes; empty for the nodes that don't run. */
        std::vector<NodeSlots> nodes{};
        std::vector<FeedbackCopy> feedbackCopies{};
        GraphLayout layout{};
    };

    struct SlotPlannerOptions {
        /** Every output is observed: a host port (the inspection compile of §5.11; tests). */
        bool observeAllOutputs = false;
        /** Outputs observed by the host, by key (`GraphLayout::OutputKey`). */
        std::set<std::string> observedOutputs{};
    };

    /** Size and ABI alignment of the LLVM type VCL emits for a VCL type, or nullopt. */
    using TypeLayoutFunction = llvm::unique_function<std::optional<std::pair<uint64_t, uint64_t>>(VCL::Type*)>;
    /** The interface of a translated source node, by node index. */
    using NodeInterfaceFunction = llvm::unique_function<const NodeInterface*(ElaboratedGraph::NodeIndex)>;

    /**
     * Plans the slots of the frame running `graph`'s execution order (§5.3). Every host region is
     * aligned to at least `minimumAlignment` (the vector width in bytes). Returns nullopt with
     * `error` set when the graph can't be planned (a mistake in the graph the user can fix);
     * `errorNode` is the node it belongs to.
     */
    std::optional<SlotPlan> PlanSlots(const ElaboratedGraph& graph, FrameKind frame, NodeInterfaceFunction interfaces,
        TypeLayoutFunction typeLayout, uint64_t minimumAlignment, const SlotPlannerOptions& options,
        std::string& error, ElaboratedGraph::NodeIndex& errorNode);

    /**
     * The plan, one line per slot use, in execution order, e.g.:
     * ```
     * g1/n2 Scale
     *   state: S1 host state g1/n2 [0, 0)
     *   in In: S4 temporary t0 float32 (g1/n1.Value, converted)
     *   out Out: S3 host port g1/n2.output [32, 36)
     * ```
     * then the layout and the temporaries' lifetimes. Tests compare it with an expected text.
     */
    std::string PrintPlan(const ElaboratedGraph& graph, const SlotPlan& plan);

}
